# tomlはpyprojectでのpythonのパッケージ設定を集約して書く　
# パッケージをビルドするツールを伝える
[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

# プロジェクトのメタデータ
[project]
name = "mazegen"
version = "1.0.0"
description = "再利用可能な迷路生成器: 入口・出口付きのグリッド迷路、追加ループの有無、'42'パターンの埋め込みに対応"
readme = "mazegen/README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "kohira" , email = "kohira@student.42tokyo.jp"},
    { name = "mkaneko" , email = "mkaneko@student.42tokyo.jp"},
]

# mazegenフォルダをカレントディレクトリから探してください指定
[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*"]

# mypyは`mypy .`実行時にpyproject.tomlを自動的に読み込むが
# Makefileのlintターゲットのコマンドは課題の指定通り変更していません。
# 以下venv/dist/build等は、自分たちが書いていないコードを対象から除外するための設定です
# 必要ないかもです
[tool.mypy]
exclude = "^(venv|\\.venv|dist|build|.*\\.egg-info)/"
